import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import MenuBack from "@/components/MenuBack";
import Navbar from "@/components/Navbar";
import TutorialOverlayPopup from "@/components/TutorialOverlayPopop";
import { useState, useEffect } from "react";

export default function Home() {

  const [data, setData] = useState([]);
  var name = process.env.NEXT_PUBLIC_NAME;
var url = `https://gis.burnaby.ca/arcgis/rest/services/OpenData/OpenData1/MapServer/6/query?where=1%3D1&outFields=*&outSR=4326&f=json${name}`
  
useEffect(() => {
  fetch(url)
  .then((res) => res.json())
  .then((info) => {
    setData(info.articles)
    console.log(info.articles)
  })
}, [])
return (
    <>
      <Head>
        <title>Skweee Well</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBack/>
      <main className={`${styles.main}`}>
        MAIN
        {name}
          {
        data.map((i, index) => {
          return(
            <div key={index}>
              {i.author}
            </div>
          )
        })
       }
        <button>
        <Link href={'/faq'}>FAQ Page</Link>
        </button>
      </main>
      <Navbar/>
    </>
  );
}
